[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.1",
    "pillow>=11.2.1",
    "setuptools>=80.9.0",
    "speechrecognition>=3.14.3",
    "werkzeug>=3.1.3",
]
